//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: bosdyn/api/spot/door_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Bosdyn_Api_Spot_DoorServiceClient`, then call methods of this protocol to make API calls.
public protocol Bosdyn_Api_Spot_DoorServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Bosdyn_Api_Spot_DoorServiceClientInterceptorFactoryProtocol? { get }

  func openDoor(
    _ request: Bosdyn_Api_Spot_OpenDoorCommandRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bosdyn_Api_Spot_OpenDoorCommandRequest, Bosdyn_Api_Spot_OpenDoorCommandResponse>

  func openDoorFeedback(
    _ request: Bosdyn_Api_Spot_OpenDoorFeedbackRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Bosdyn_Api_Spot_OpenDoorFeedbackRequest, Bosdyn_Api_Spot_OpenDoorFeedbackResponse>
}

extension Bosdyn_Api_Spot_DoorServiceClientProtocol {
  public var serviceName: String {
    return "bosdyn.api.spot.DoorService"
  }

  /// Unary call to OpenDoor
  ///
  /// - Parameters:
  ///   - request: Request to send to OpenDoor.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func openDoor(
    _ request: Bosdyn_Api_Spot_OpenDoorCommandRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bosdyn_Api_Spot_OpenDoorCommandRequest, Bosdyn_Api_Spot_OpenDoorCommandResponse> {
    return self.makeUnaryCall(
      path: "/bosdyn.api.spot.DoorService/OpenDoor",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpenDoorInterceptors() ?? []
    )
  }

  /// Unary call to OpenDoorFeedback
  ///
  /// - Parameters:
  ///   - request: Request to send to OpenDoorFeedback.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func openDoorFeedback(
    _ request: Bosdyn_Api_Spot_OpenDoorFeedbackRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Bosdyn_Api_Spot_OpenDoorFeedbackRequest, Bosdyn_Api_Spot_OpenDoorFeedbackResponse> {
    return self.makeUnaryCall(
      path: "/bosdyn.api.spot.DoorService/OpenDoorFeedback",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpenDoorFeedbackInterceptors() ?? []
    )
  }
}

public protocol Bosdyn_Api_Spot_DoorServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'openDoor'.
  func makeOpenDoorInterceptors() -> [ClientInterceptor<Bosdyn_Api_Spot_OpenDoorCommandRequest, Bosdyn_Api_Spot_OpenDoorCommandResponse>]

  /// - Returns: Interceptors to use when invoking 'openDoorFeedback'.
  func makeOpenDoorFeedbackInterceptors() -> [ClientInterceptor<Bosdyn_Api_Spot_OpenDoorFeedbackRequest, Bosdyn_Api_Spot_OpenDoorFeedbackResponse>]
}

public final class Bosdyn_Api_Spot_DoorServiceClient: Bosdyn_Api_Spot_DoorServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Bosdyn_Api_Spot_DoorServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the bosdyn.api.spot.DoorService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Bosdyn_Api_Spot_DoorServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Bosdyn_Api_Spot_DoorServiceProvider: CallHandlerProvider {
  var interceptors: Bosdyn_Api_Spot_DoorServiceServerInterceptorFactoryProtocol? { get }

  func openDoor(request: Bosdyn_Api_Spot_OpenDoorCommandRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Bosdyn_Api_Spot_OpenDoorCommandResponse>

  func openDoorFeedback(request: Bosdyn_Api_Spot_OpenDoorFeedbackRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Bosdyn_Api_Spot_OpenDoorFeedbackResponse>
}

extension Bosdyn_Api_Spot_DoorServiceProvider {
  public var serviceName: Substring { return "bosdyn.api.spot.DoorService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "OpenDoor":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Bosdyn_Api_Spot_OpenDoorCommandRequest>(),
        responseSerializer: ProtobufSerializer<Bosdyn_Api_Spot_OpenDoorCommandResponse>(),
        interceptors: self.interceptors?.makeOpenDoorInterceptors() ?? [],
        userFunction: self.openDoor(request:context:)
      )

    case "OpenDoorFeedback":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Bosdyn_Api_Spot_OpenDoorFeedbackRequest>(),
        responseSerializer: ProtobufSerializer<Bosdyn_Api_Spot_OpenDoorFeedbackResponse>(),
        interceptors: self.interceptors?.makeOpenDoorFeedbackInterceptors() ?? [],
        userFunction: self.openDoorFeedback(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Bosdyn_Api_Spot_DoorServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'openDoor'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeOpenDoorInterceptors() -> [ServerInterceptor<Bosdyn_Api_Spot_OpenDoorCommandRequest, Bosdyn_Api_Spot_OpenDoorCommandResponse>]

  /// - Returns: Interceptors to use when handling 'openDoorFeedback'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeOpenDoorFeedbackInterceptors() -> [ServerInterceptor<Bosdyn_Api_Spot_OpenDoorFeedbackRequest, Bosdyn_Api_Spot_OpenDoorFeedbackResponse>]
}
